### ISSUE TITLE
Inserting ins and del tags

### ISSUE THREAD

**Issue by deyayan** [krajzeg/hiff#14]
How can we insert the ins and del tags around the removed, added texts? I just can't seem to find a way for it.

**Comment by krajzeg** [comment]
After doing the comparison, you can use the `changes` property along with either `$before` or `$after` to edit your tags in. There is no automated functionality for this, so you'll have to use [cheerio](https://www.npmjs.com/package/cheerio) functionality to do that yourself. The change objects (described in the README) have enough information to implement that.
